version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: php_test_mysql
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: simple_psw
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: simple_psw
    ports:
      - 9906:3306
    volumes:
      - ./data:/var/lib/mysql
 
  php-myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php_test_myadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306 
    links:
      - db:mysql

  app:
    build: . 
    image: php_apache_pdo
    container_name: php_test_app
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - 8080:80
    stdin_open: true
    tty: true


