version: '2.0'

services:

  app:
    build: 
      context: ./bin/app
    image: php_apache_pdo
    container_name: php_test_app
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - 8080:80
    stdin_open: true
    tty: true

  db:
    build: 
      context: ./bin/db
    image: populated_mysql
    container_name: php_test_mysql
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: simple_psw
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: simple_psw
    ports:
      - 9906:3306
    volumes:
      - ./bin/db/sql-scripts:/docker-entrypoint-initdb.d/
      - mysql:/var/lib/mysql
      
  php-myadmin:
    image: phpmyadmin/phpmyadmin:4.8
    container_name: php_test_myadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306 
    links:
      - db:mysql


# using this named volume ensures db's hang around between "up's"
volumes:
    mysql:


