version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: php_test_mysql
    environment:
      MYSQL_ROOT_PASSWORD: simple_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: simple_password
    ports:
      - 9906:3306
    volumes:
      - ./data/:/var/lib/mysql

  app:
    build: . 
    image: php_apache_pdo
    container_name: php_test_app
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - 8080:80
    stdin_open: true
    tty: true

    